apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops_project5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops_project5
  template:
    metadata:
      labels:
        app: devops_project5
    spec:
      containers:
        - name: devops_project5
          image: 0399468055/devops_project5:latest
          ports:
            - containerPort: 8080
